Refactor + update BaseEmbedder emebedding methods
MaartenGr/BERTopic pull request #855
Opened 2022-11-24 16:18 UTC by zachschillaci27

Refactor and update the various `BaseEmbedder` subclasses, specifically focusing on the `embed` methods. The changes are summarized for each subclass below:
- `FlairBackend`: Replace unused `index` with `_`
- `GensimBackend`: Change handling of out-of-vocabulary words from assigning the zero vector to skipping. Directly compute the mean over word vectors using a list comprehension.
- `SentenceTransformerBackend`: Directly return `embeddings`.
- `SpacyBackend`: Avoid bare `except` (risky) and change handling of empty documents. Though I'm not certain the empty document checks are necessary - what were the original exceptions being raised?
- `USEBackend`: Directly return `embeddings`.

Please let me know if you have any comments or feedback!

2022-12-06 08:32 UTC, MaartenGr commented
Thank you for the PR and apologies for the late reply. I'll take some time to look things over.

2022-12-06 08:39 UTC, MaartenGr commented
Other than the things mentioned above, there are some real nice refactors there!

2022-12-08 13:50 UTC, zachschillaci27 commented
> Other than the things mentioned above, there are some real nice refactors there!

Thanks! Let me know if you would like me to change anything

2022-12-10 08:08 UTC, MaartenGr commented
> Thanks! Let me know if you would like me to change anything

Yes, the things I mentioned above would be great if you could update them.

2022-12-10 09:18 UTC, zachschillaci27 commented
> > Thanks! Let me know if you would like me to change anything
> 
> 
> 
> Yes, the things I mentioned above would be great if you could update them. 

Sorry, not sure I see any comments. Where did you write them? 😅

2022-12-13 08:47 UTC, MaartenGr requested changes

2022-12-13 08:48 UTC, MaartenGr commented
> Sorry, not sure I see any comments. Where did you write them? 😅

Oops, my bad! You should see them now.

2022-12-13 09:30 UTC, zachschillaci27 commented on bertopic/backend/_flair.py
> +        for _, document in tqdm(enumerate(documents), disable=not verbose):
I completely agree! I left it in case it was intended to serve some other purpose.

2022-12-13 09:34 UTC, zachschillaci27 commented on bertopic/backend/_gensim.py
> +                        for word in doc.split()
Actually, there are some subtle differences between the two, see [here](https://stackoverflow.com/questions/60446017/what-is-difference-of-split-and-split). In which case, I figured `doc.split()` is the preferred option to better handle the splitting of multiple/trailing white spaces. Let me know what you think.

2022-12-19 05:53 UTC, MaartenGr commented on bertopic/backend/_gensim.py
> +                        for word in doc.split()
Great, totally missed that! Let's keep your suggestion.

2022-12-19 06:16 UTC, MaartenGr approved these changes

2022-12-19 06:17 UTC, merged

2022-12-19 06:18 UTC, MaartenGr commented
@zachschillaci27 Thanks for the work! I just merged it 😄